color0 #161215
color1 #ffb4ab
color2 #ffabf3
color3 #dabfd2
color4 #f5b8a7
color5 #ffabf3
color6 #dabfd2
color7 #e9e0e4
color8 #9a8d95
color9 #ffb4ab
color10 #ffabf3
color11 #dabfd2
color12 #f5b8a7
color13 #ffabf3
color14 #dabfd2
color15 #e9e0e4

cursor                #e9e0e4
cursor_text_color     #161215
background            #161215
foreground            #e9e0e4
selection_foreground  #d1c2cb
selection_background  #4e444b
active_border_color   #ffabf3
inactive_border_color #4e444b
url_color             #ffabf3

active_tab_foreground   #551353
active_tab_background   #ffabf3
inactive_tab_foreground #d1c2cb
inactive_tab_background #4e444b
cursor_trail_color      #d1c2cb
