color0 #111416
color1 #ffb4ab
color2 #7fd0ff
color3 #b6c9d8
color4 #cbc1e9
color5 #7fd0ff
color6 #b6c9d8
color7 #e1e2e5
color8 #8b9297
color9 #ffb4ab
color10 #7fd0ff
color11 #b6c9d8
color12 #cbc1e9
color13 #7fd0ff
color14 #b6c9d8
color15 #e1e2e5

cursor                #e1e2e5
cursor_text_color     #111416
background            #111416
foreground            #e1e2e5
selection_foreground  #c1c7ce
selection_background  #41484d
active_border_color   #7fd0ff
inactive_border_color #41484d
url_color             #7fd0ff

active_tab_foreground   #00344a
active_tab_background   #7fd0ff
inactive_tab_foreground #c1c7ce
inactive_tab_background #41484d
cursor_trail_color      #c1c7ce
