SOUNDS_DIR=$NIRI_DIR/sounds/steam

SND_WINDOW_OPEN=$SOUNDS_DIR/bookOpen.ogg
SND_WINDOW_OPEN_VOL=1.0
SND_WINDOW_CLOSE=$SOUNDS_DIR/bookClose.ogg
SND_WINDOW_CLOSE_VOL=1.0
SND_WORKSPACE=$SOUNDS_DIR/steam_deck_ui_tab_transition_01.wav
SND_WORKSPACE_VOL=1.0
SND_OVERVIEW=$SOUNDS_DIR/message-new-instant.oga
SND_OVERVIEW_VOL=1.0
SND_MEDIA_START=$SOUNDS_DIR/steam_deck_ui_launch_game.wav
SND_MEDIA_START_VOL=1.0

TYPING_APPS=( "kitty" "org.gnome.Nautilus" "dev.zed.Zed" "org.telegram.desktop" )

TYPING_VOLUME=1.0
NIGHT_START=20
NIGHT_END=7
NIGHT_VOLUME=0.6
CAPS_VOLUME=3.0

SND_TYPING_TYPING=( "$SOUNDS_DIR/steam_deck_ui_typing.wav" )
SND_TYPING_TYPING_VOL=1.0
SND_TYPING_ACTION=( "$SOUNDS_DIR/steam_deck_ui_typing.wav" )
SND_TYPING_ACTION_VOL=1.0
SND_TYPING_MODIFIER=()
SND_TYPING_MODIFIER_VOL=1.0
SND_TYPING_FUNCTION=()
SND_TYPING_FUNCTION_VOL=1.0
SND_TYPING_NAV=()
SND_TYPING_NAV_VOL=1.0
