SOUNDS_DIR=$NIRI_DIR/sounds/test

SND_WINDOW_OPEN=
SND_WINDOW_CLOSE=
SND_WORKSPACE=
SND_OVERVIEW=
SND_MEDIA_START=

TYPING_APPS=()

TYPING_VOLUME=1.0
NIGHT_START=22
NIGHT_END=7
NIGHT_VOLUME=0.3
CAPS_VOLUME=1.0

SND_TYPING_TYPING=()
SND_TYPING_ACTION=()
SND_TYPING_MODIFIER=()
SND_TYPING_FUNCTION=()
SND_TYPING_NAV=()
